# Generated by Django 4.1.6 on 2023-03-20 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_scope_alter_article_options_tag_scope_article_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scope",
            options={
                "default_related_name": "scopes",
                "verbose_name": "Раздел",
                "verbose_name_plural": "Тематики статьи",
            },
        ),
        migrations.AddField(
            model_name="scope",
            name="name",
            field=models.CharField(default="", max_length=50, verbose_name="Тег"),
        ),
        migrations.AlterField(
            model_name="scope",
            name="is_main",
            field=models.BooleanField(default=False, verbose_name="Основной тег"),
        ),
        migrations.CreateModel(
            name="TagsNews",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article",
                    models.ManyToManyField(related_name="tags", to="articles.article"),
                ),
            ],
            options={
                "verbose_name": "Тег новостей",
                "verbose_name_plural": "Теги новостей",
            },
        ),
        migrations.AlterField(
            model_name="scope",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scopes",
                to="articles.tagsnews",
                verbose_name="Раздел",
            ),
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
