# Generated by Django 4.1.6 on 2023-03-20 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "articles",
            "0003_alter_scope_options_scope_name_alter_scope_is_main_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Тег")),
            ],
            options={
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
            },
        ),
        migrations.CreateModel(
            name="TagsArticle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(default=False, verbose_name="Основной"),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scopes",
                        to="articles.article",
                        verbose_name="Статья",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="articles.tags",
                        verbose_name="Тег",
                    ),
                ),
            ],
            options={
                "verbose_name": "Связи m2m",
                "verbose_name_plural": "Связь Тег - Статья",
                "ordering": ["-is_main", "tag__name"],
            },
        ),
        migrations.RemoveField(
            model_name="tagsnews",
            name="article",
        ),
        migrations.DeleteModel(
            name="Scope",
        ),
        migrations.DeleteModel(
            name="TagsNews",
        ),
    ]
